import vectorbt as vbt
import pandas as pd

from backtest.backtester import Backtester

START_DATE = '2016-02-01'
END_DATE = '2020-08-12'


def algo(all_data: pd.DataFrame) -> list[str]:
  # return ['BIL']
  xlk_rsi = vbt.RSI.run(all_data['XLK'], window=10, short_name="rsi", ewm=True).rsi[-1]
  kmlm_rsi = vbt.RSI.run(all_data['KMLMX'], window=10, short_name="rsi", ewm=True).rsi[-1]
  if xlk_rsi > kmlm_rsi:
    return ['TECL']
  else:
    return ['BIL']

def spy(_all_data: pd.DataFrame) -> list[str]:
  return ['SPY']


backtester = Backtester()

all_stocks = list(set(['KMLMX', 'SPY', 'TECL', 'XLK', 'BIL']))
portfolio = backtester.run_backtest(all_stocks, algo, START_DATE, END_DATE)

spy_stock = list(['SPY'])
spy_portfolio = backtester.run_backtest(spy_stock, spy, START_DATE, END_DATE)

# Print VectorBT stats and show the plot
print(f"""
VectorBT result:
{portfolio.stats()}
""")
# portfolio.plot().show()

# Save the tear sheet generated by QuantStats
backtester.gen_tear_sheet(portfolio, spy_portfolio, "/Users/jchan/projects/stock_recommendation/backtest/tear_sheet.html")


# To run from backtest/ directory:
# python3 kmlmx.py
